const GET_USER_PERMISSION = 'getUser';
const GET_ABOUT_USER_PERMISSION = 'getAboutUser';
const ADD_USER_PERMISSION = 'addUser';
const DELETE_USER_PERMISSION = 'deleteUser';
const EDIT_USER_PERMISSION = 'editUser';

const ADD_PRODUCT_PERMISSION = 'addProduct';
const DELETE_PRODUCT_PERMISSION = 'deleteProduct';
const EDIT_PRODUCT_PERMISSION = 'editProduct';

const GET_GROUP_PERMISSION = 'getGroup';
const EDIT_GROUP_PERMISSION = 'editGroup';
const ADD_GROUP_PERMISSION = 'addGroup';
const DELETE_GROUP_PERMISSION = 'deleteGroup';

const GET_REQUEST_PERMISSION = 'getRequest';
const ADD_REQUEST_PERMISSION = 'addRequest';
const DELETE_REQUEST_PERMISSION = 'deleteRequest';
const EDIT_REQUEST_PERMISSION = 'editRequest';
const CLOSE_REQUEST_PERMISSION = 'closeRequest';

const VIEW_HISTORY_PERMISSION = 'viewHistory';
const GET_STATISTIC_PERMISSION = 'getStatistic';

const GET_TRASH = 'getTrash';

module.exports = [
    GET_USER_PERMISSION
    , ADD_USER_PERMISSION
    , DELETE_USER_PERMISSION
    , EDIT_USER_PERMISSION
    , GET_ABOUT_USER_PERMISSION

    , ADD_PRODUCT_PERMISSION
    , DELETE_PRODUCT_PERMISSION
    , EDIT_PRODUCT_PERMISSION

    , GET_GROUP_PERMISSION
    , EDIT_GROUP_PERMISSION
    , ADD_GROUP_PERMISSION
    , DELETE_GROUP_PERMISSION

    , GET_REQUEST_PERMISSION
    , ADD_REQUEST_PERMISSION
    , DELETE_REQUEST_PERMISSION
    , EDIT_REQUEST_PERMISSION
    , CLOSE_REQUEST_PERMISSION

    , VIEW_HISTORY_PERMISSION
    , GET_STATISTIC_PERMISSION

    , GET_TRASH
];
