const p = require('./permissions')

module.exports = [
    p.GET_USER_PERMISSION,
    p.ADD_USER_PERMISSION,
    p.DELETE_USER_PERMISSION,
    p.EDIT_USER_PERMISSION,

    p.ADD_PRODUCT_PERMISSION,
    p.DELETE_PRODUCT_PERMISSION,
    p.EDIT_PRODUCT_PERMISSION,

    p.GET_GROUP_PERMISSION,
    p.EDIT_GROUP_PERMISSION,
    p.ADD_GROUP_PERMISSION,
    p.DELETE_GROUP_PERMISSION,

    p.GET_REQUEST_PERMISSION,
    p.ADD_REQUEST_PERMISSION,
    p.DELETE_REQUEST_PERMISSION,
    p.EDIT_REQUEST_PERMISSION,
    p.CLOSE_REQUEST_PERMISSION,

    p.VIEW_HISTORY_PERMISSION,
    p.GET_STATISTIC_PERMISSION,
];
