export const wordList = {
    ru: {
        necessarily: 'Обязательно',
        notNecessary: 'Не обязательно',
        search: 'Поиск',
        productList: {
            photo: 'Фото',
            name: 'Имя',
            quantity: 'Количество',
            productType: 'Тип',
            price: 'Цена',
            isRefrigeratorRequired: 'Наличие холодильника для перевозки',
            searchProduct: 'Поиск продуктов',
            addNewProduct: 'Добавить новые продукты',
            productListTitle: 'Список продуктов',
            statisticBtn: 'Смотреть статистику',
            statLabel: 'Количество дней',
            errorMessage: 'Пожалуйста введите данные'
        },
        loginBtn: 'Вход',
        authUserToolBar: {
            requestBtn: 'Подать заявку',
            greeting: 'Привет',
            logoutBtn: 'Выйти',
            accountBtn: 'Информация об аккаунте',
            statisticBtn: 'Моя статистика'
        },
        navigation: {
            logo: 'Караван',
            groupList: 'Группы',
            userList: 'Пользователи',
            requestList: 'Список заявок',
            historyList: 'История'
        },
        login: {
            loginTitle: 'Вход',
            loginBtn: 'Войти',
            userTitle: 'Имя пользователя',
            password: 'Пароль',
            usernamePlaceholder: 'Введите имя пользователя',
            passwordPlaceholder: 'Введите пароль'
        },
        usersList: {
            searchTitle: 'Поиск пользователя',
            addUserBtn: 'Добавить пользователя',
            tableName: 'Имя',
            tableLogin: 'Логин',
            tablePhone: 'Телефон',
            tableCompanyName: 'Название компании',
            tableAddress: 'Адрес',
            tableRole: 'Роль',
            tableCarName: 'Название машины',
            tableCarVolume: 'Объем машины',
            tableRefrigerator: 'Наличие холодильника',
            tableRefrigeratorAvailability: 'Есть',
            listItemUsers: 'Все',
            searchRole: 'Поиск по ролям'
        },
        groupsList: {
            listGroupTitle: 'Список групп',
            addGroupBtn: 'Добавить группу',
            tableGroupTitle: 'Название',
            tableGroupQty: 'Количество участников',
            addUsersBtn: 'Просмотреть группу'
        },
        groupInfo: {
            info: 'Информация о группе',
            groupTitle: 'Название группы',
            groupPermits: 'Список разрешений',
            groupUsers: 'Участники',
            groupUserName: 'Имя',
            groupUserInfo: 'Информация о пользователе',
            addUserToGroup: 'Пользователи которых можно добавить',
            addUserToGroupUserName: 'Имя',
            addUserToGroupInfo: 'Информация',
            addUserToGroupBtn: 'Добавить в группу',
            editGroupBtn: 'Редактировать',
            deleteGroupBtn: 'Удалить группу',
            deleteModal: 'Вы уверены что хотите удалить эту группу?',
            deleteBtnNeg: 'Нет',
            deleteBtnPos: 'Да',
        },
        addGroup: {
            addGroupTitle: 'Добавление новой группы',
            addGroupName: 'Название группы',
            addGroupBtn: 'Добавить'
        },
        addNewRequest: {
            productsBtn: 'Доступный товар',
            createRequestTitle: 'Создать заявку',
            commentTitle: 'Комментарий',
            addRequestBtn: 'Добавить',
            createRequestBtn: 'Создать заявку',
            error: 'В одном из продуктов заявки вы выбрали больше товара, чем имеется на складе!',
            totalPrice: 'Общая цена: '
        },
        addNewRequestItem: {
            btnTitle: 'Название',
            btnQty: 'Количество',
            productQty: 'На складе есть: '
        },
        addProduct: {
            addProductTitle: 'Добавление продуктов',
            addProductBtn: 'Добавить',
            createProductBtn: 'Сохранить',
        },
        addProductItem: {
            inputTitle: 'Название',
            inputQty: 'Количество',
            inputType: 'Тип продукта',
            inputPrice: 'Цена',
            inputRefrigerator: 'Необходим ли холодильник для перевозки?',
            inputImg: 'Изображение',
            inputComment: 'Причина добавления',
        },
        addUser: {
            addUserTitle: 'Добавление нового пользователя',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Отображаемое имя',
            inputRole: 'Роль',
            inputCarName: 'Марка машины',
            inputCarVolume: 'Объем машины',
            inputRefrigerator: 'Наличие холодильника',
            inputCompanyName: 'Название компании',
            inputCompanyAddress: 'Адрес компании',
            inputCoordinates: 'Координаты',
            inputAvatar: 'Avatar',
            inputComment: 'Причина добавления',
            addBtn: 'Добавить',
            addUserToGroupLabel: 'Добавить в группы'
        },
        editProduct: {
            editProductTitle: 'Редактирование продукта',
            inputTitle: 'Название',
            inputQty: 'Сколько нужно добавить продуктов',
            inputPrice: 'Цена',
            inputRefrigerator: 'Необходим ли холодильник для перевозки?',
            inputImg: 'Изображение',
            editProductBtn: 'Редактировать',
            deleteProductBtn: 'Удалить',
            modalDeleteTitle: 'Вы уверены что хотите удалить этот продукт?',
            modalComment: 'Комментарий',
            modalBtnNeg: 'Нет',
            modalBtnPos: 'Да',
            modalEditTitle: 'Вы уверены что хотите отредактировать этот продукт?',
            availableProductQty: 'На складе есть: '
        },
        editRequest: {
            editRequestTitle: 'Редактировать заявку',
            inputComment: 'Комментарий',
            addRequestBtn: 'Добавить',
            editRequestBtn: 'Редактировать заявку',
            deleteRequestBtn: 'Удалить заявку',
            modalEditTitle: 'Вы уверены что хотите удалить эту заявку?',
            modalBtnNeg: 'Нет',
            modalBtnPos: 'Да',
            error: 'В одном из продуктов заявки вы выбрали больше товара чем имеется на складе!'
        },
        editRequestItems: {
            title: 'Название: ',
            qty: 'Количество: ',
            chooseProd: 'Выберите продукт',
            inputQty: 'Количество',
            storageQty: 'На складе есть:'
        },
        editUser: {
            editUserTitle: 'Редактирование пользователя',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Отображаемое имя',
            inputRole: 'Роль',
            inputCarName: 'Название машины',
            inputCarVolume: 'Объем машины',
            inputRefrigerator: 'Наличие холодильника',
            inputCompanyName: 'Название компании',
            inputCompanyAddress: 'Адрес компании',
            inputAvatar: 'Avatar',
            inputEditComment: 'Причина редактирования',
            editBtn: 'Редактировать',
            deleteBtn: 'Удалить пользователя',
            modalDeleteTitle: 'Вы уверены что хотите удалить этого пользователя?',
            inputDeleteComment: 'Причина удаления',
            modalBtnNeg: 'Нет',
            modalBtnPos: 'Да',
        },
        histories: {
            tableInfo: 'Информация',
            tableComment: 'Комментарий',
            tableType: 'Тип',
            tableDate: 'Дата',
            deleteLabel: 'Удаление',
            addLabel: 'Добавление',
            editLabel: 'Редактирование',
            title: 'В истории пока ничего нет',
            editType: 'редактировал',
            deleteType: 'удалил',
            addType: 'добавил'
        },
        requestInfo: {
            requestInfoTitle: 'Информация о заявке',
            requestInfoUser: 'Пользователь',
            requestInfoPhone: 'Телефон',
            requestInfoDate: 'Дата создания',
            requestInfoStatus: 'Статус',
            requestInfoMarket: 'Магазин',
            requestInfoAddress: 'Адрес',
            requestInfoCoord: 'Координаты',
            requestInfoProducts: 'Продукты',
            requestInfoProductsTitle: 'Название',
            requestInfoProductsQty: 'Количество',
            requestInfoRefrigerator: 'Холодильник',
            refrigeratorNec: 'Нужен',
            refrigeratorNotNec: 'Не нужен',
            closeBtn: 'Закрыть заявку',
            requestInfoCourier: 'Назначенный курьер',
            requestInfoCourierDate: 'Дата назначения',
            courierName: 'Имя',
            courierPhone: 'Телефон',
            courierInfo: 'Информация о курьере',
            deleteCourierBtn: 'Удалить курьера',
            nominateCourierBtn: 'Назначить экспедитору',
            fridgeAvail: 'Есть',
            fridgeNotAvail: 'Отсутствует',
            nomBtn: 'Назначить',
            deleteClosedRequest: 'Удалить заявку',
            modal: 'Выберите экспедитора'
        },
        requestList: {
            tableUser: 'Пользователь',
            tableDate: 'Дата',
            tableStatus: 'Статус',
        },
        requestListItem: {
            label_1: 'В ожидании',
            label_2: 'Выполняется',
            label_3: 'Закрыт'
        },
        userInfo: {
            userInfoTitle: 'Информация о пользователе',
            userInfoRole: 'Роль',
            userInfoName: 'Пользователь',
            userInfoPhone: 'Телефон',
            userInfoMarket: 'Магазин',
            userInfoAddress: 'Адрес',
            userInfoCoord: 'Координаты',
            userInfoCar: 'Машина',
            userInfoCarVolume: 'Объем машины',
            userInfoFridge: 'Наличие холодильника',
            fridgeAvail: 'Есть',
            fridgeNotAvail: 'Отсутствует',
            groupsList: 'Список групп',
            permissionsList: 'Список разрешений'
        },
        productsActions: {
            addProductTitle: 'Добавление продукта',
            addProductMessage: 'Продукт добавлен успешно',
            editProductTitle: 'Редактирование',
            editProductMessage: 'Продукт успешно изменён',
            deleteProductTitle: 'Удаление',
            deleteProductMessage: 'Продукт успешно удален'
        },
        usersActions: {
            loginUserTitle: 'Логин',
            loginUserMessage: 'Вы успешно вошли, как ',
            logoutUserTitle: 'Выход',
            logoutUserMessage: 'Вы успешно покинули свой аккаунт',
            addUserTitle: 'Добавление пользователя',
            addUserMessage: 'Пользователь успешно добавлен',
            deleteUserTitle: 'Удаление пользователя',
            deleteUserMessage: 'Пользователь успешно удален'
        },
        requestsActions: {
            createRequestTitle: 'Создание заявки',
            createRequestMessage: 'Заявка создана успешно',
            editRequestTitle: 'Редактирование',
            editRequestMessage: 'Заявка успешно отредактирована',
            deleteRequestTitle: 'Удаление',
            deleteRequestMessage: 'Заявка успешно удалена'
        },
        statistic: {
            statisticTitle: 'Статистика покупок',
            statisticSearchFieldTitle: 'Получить статистику за указанное количество дней',
            salesStatistics: 'Статистика продаж',
            optionName1: 'Продукты',
            optionName2: 'Пользователи',
            labelType: 'Тип',
            labelDoc: 'Документ',
            labelFrom: 'От',
            labelTo: 'До',
        },
        editGroup: {
            title: 'Название',
            btn: 'Редактировать'
        },
        groupActions: {
            addGroupTitle: 'Добавление группы',
            addGroupMessage: 'Группа успешно добавлена!'
        },
        trash: {
            trashTitle: 'Корзина',
            emptyTrashTitle: 'Корзина пока пуста',
            trashType1: 'Все',
            trashType2: 'Пользователи',
            trashType3: 'Заявки',
            trashType4: 'Продукты',
            trashType5: 'Группы',
            btnType1: 'От нового к старому',
            btnType2: 'От старого к новому',
            autoCompleteLabel: 'Фильтр по типу',
            tableTitle: 'Название',
            tableDate: 'Дата',
            request: 'Заявка'
        },
        mainPageMap: {
            title: 'Карта торговых точек'
        }
    },


    kg: {
        necessarily: 'Сөзсүз',
        notNecessary: 'Кереги жок',
        search: 'издөө',
        productList: {
            photo: 'Сүрөт',
            name: 'Наам',
            quantity: 'Сан',
            productType: 'Түрү',
            price: 'Баа',
            isRefrigeratorRequired: 'Ташуу үчүн муздаткычтын болушу',
            searchProduct: 'Продукцияны издөө',
            addNewProduct: 'Жаңы продукттарды кошуу',
            productListTitle: 'Продукт тизмеси',
            statisticBtn: 'Статистиканы көрүү',
            statLabel: 'Күндүн саны',
            errorMessage: 'Сураныч маалыматтарды киргизиңиз'
        },
        loginBtn: 'Кирүү',
        authUserToolBar: {
            requestBtn: 'Өтүнүч берүү',
            greeting: 'Салам',
            logoutBtn: 'Чыгуу',
            accountBtn: 'Колдонуучунун маалыматы',
            statisticBtn: 'Менин статистикам'
        },
        navigation: {
            logo: 'Караван',
            groupList: 'Топтор',
            userList: 'Колдонуучулар',
            requestList: 'Өтүнүчтөр',
            historyList: 'Тарыхы'
        },
        login: {
            loginTitle: 'Кирүү',
            loginBtn: 'Кирүү',
            userTitle: 'Колдонуучунун аты',
            password: 'Пароль',
            usernamePlaceholder: 'Колдонуучунун атын киргизгиле',
            passwordPlaceholder: 'Пароль киргизгиле'
        },
        usersList: {
            searchTitle: 'Колдонуучуну издөө',
            addUserBtn: 'Колдонуучуну кошуу',
            tableName: 'Аты',
            tableLogin: 'Логин',
            tablePhone: 'Телефон',
            tableCompanyName: 'Компаниянын аты',
            tableAddress: 'Дареги',
            tableRole: 'Кызматы',
            tableCarName: 'Унаанын аты',
            tableCarVolume: 'Унаанын көлөмү',
            tableRefrigerator: 'Муздаткычтын катышуусу',
            tableRefrigeratorAvailability: 'Бар',
            listItemUsers: 'Баары',
            searchRole: 'Кызматты издөө'
        },
        groupsList: {
            listGroupTitle: 'Топтордун тизмеси',
            addGroupBtn: 'Тобун кошуу',
            tableGroupTitle: 'Аты',
            tableGroupQty: 'Катышуучулардын саны',
            addUsersBtn: 'Колдонуучуларды кошуу'
        },
        groupInfo: {
            info: 'Тобунун маалыматы',
            groupTitle: 'Тобунун аты',
            groupPermits: 'Уруксаттардын тизмеси',
            groupUsers: 'Катышуучулар',
            groupUserName: 'Аты',
            groupUserInfo: 'Катышуучунун маалыматы',
            addUserToGroup: 'Колдонуучуларды кошо аласыз',
            addUserToGroupUserName: 'Аты',
            addUserToGroupInfo: 'Маалымат',
            addUserToGroupBtn: 'Тобуна кошуу',
            editGroupBtn: 'Түзөө',
            deleteGroupBtn: 'Тобун жок кылуу',
            deleteModal: 'Бул топту чын эле жок кылгыңыз келеби?',
            deleteBtnNeg: 'Жок',
            deleteBtnPos: 'Ооба',
        },
        addGroup: {
            addGroupTitle: 'Жаңы топ кошуу',
            addGroupName: 'Тобунун аты',
            addGroupBtn: 'Кошуу'
        },
        addNewRequest: {
            productsBtn: 'Жеткиликтүү продукттар',
            createRequestTitle: 'Өтүнүч түзүү',
            commentTitle: 'Түшүндүрмө',
            addRequestBtn: 'Кошуу',
            createRequestBtn: 'Өтүнүч түзүү',
            error: 'Колдонмонун продукттун биринде сиз кампага караганда көбүрөөк товарды тандадыңыз!',
            totalPrice: 'Жалпы баа: '
        },
        addNewRequestItem: {
            btnTitle: 'Аты',
            btnQty: 'Саны',
            productQty: 'Сактоочу бөлмөдө: '
        },
        addProduct: {
            addProductTitle: 'Продуктту кошуу',
            addProductBtn: 'Кошуу',
            createProductBtn: 'Түзүү',
        },
        addProductItem: {
            inputTitle: 'Аты',
            inputQty: 'Саны',
            inputType: 'Продуктун түрү',
            inputPrice: 'Баа',
            inputRefrigerator: 'Ташуу үчүн муздаткыч керекпи?',
            inputImg: 'Сүрөт',
            inputComment: 'Кошуунун себеби',
        },
        addUser: {
            addUserTitle: 'Жаңы колдонуучу кошуу',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Аты',
            inputRole: 'Кызматы',
            inputCarName: 'Унаанын модели',
            inputCarVolume: 'Унаанын көлөмү',
            inputRefrigerator: 'Муздаткычтын болушу',
            inputCompanyName: 'Компаниянын аты',
            inputCompanyAddress: 'Компаниянын дареги',
            inputCoordinates: 'Координаттар',
            inputAvatar: 'Avatar',
            inputComment: 'Кошуунун себеби',
            addBtn: 'Кошуу',
            addUserToGroupLabel: 'Топторго кошуу'
        },
        editProduct: {
            editProductTitle: 'Продуктту түзөтүү',
            inputTitle: 'Аты',
            inputQty: 'Канча продуктту кошсо керек',
            inputPrice: 'Баасы',
            inputRefrigerator: 'Ташуу үчүн муздаткыч керекпи?',
            inputImg: 'Сүрөтү',
            editProductBtn: 'Түзөө',
            deleteProductBtn: 'Жок кылуу',
            modalDeleteTitle: 'Бул продуктту чын эле алып салгыңыз келеби?',
            modalComment: 'Түшүндүрмө',
            modalBtnNeg: 'Жок',
            modalBtnPos: 'Ооба',
            modalEditTitle: 'Бул продуктту чын эле түзөткүңүз келеби?',
            availableProductQty: 'Товар сактоочу бөлмөдө: '
        },
        editRequest: {
            editRequestTitle: 'Өтүнүчтү түзөтүү',
            inputComment: 'Түшүндүрмө',
            addRequestBtn: 'Кошуу',
            editRequestBtn: 'Өтүнүчтү түзөтүү',
            deleteRequestBtn: 'Өтүнүчтү жок кылуу',
            modalBtnNeg: 'Жок',
            modalBtnPos: 'Ооба',
            modalEditTitle: 'Бул өтүнүчтү  чын эле алып салгыңыз келеби?',
            error: 'Колдонмонун продукттун биринде сиз кампага караганда көбүрөөк товарды тандадыңыз!'
        },
        editRequestItems: {
            title: 'Аты: ',
            qty: 'Саны: ',
            chooseProd: 'Продуктту тандаңыз',
            inputQty: 'Саны',
            storageQty: 'Кампада:'
        },
        editUser: {
            editUserTitle: 'Колдонуучу түзөтүүсү',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Аты',
            inputRole: 'Кызматы',
            inputCarName: 'Унаанын модели',
            inputCarVolume: 'Унаанын көлөмү',
            inputRefrigerator: 'Муздаткычтын болушу',
            inputCompanyName: 'Компаниянын аты',
            inputCompanyAddress: 'Компаниянын дареги',
            inputAvatar: 'Avatar',
            inputEditComment: 'Түзөтүүнүн себеби',
            editBtn: 'Түзөө',
            deleteBtn: 'Колдонуучуну жок кылуу',
            modalDeleteTitle: 'Чын эле бул колдонуучуну жок кылгыңыз келеби?',
            inputDeleteComment: 'Жок кылуунун себеби',
            modalBtnNeg: 'Жок',
            modalBtnPos: 'Ооба',
        },
        histories: {
            tableInfo: 'Маалымат',
            tableComment: 'Түшүндүрмө',
            tableType: 'Түрү',
            tableDate: 'Датасы',
            deleteLabel: 'Жок кылуу',
            addLabel: 'Кошуу',
            editLabel: 'Түзөтүү',
            title: 'Азырынча тарыхта эч нерсе жок',
            editType: 'түзөттү',
            deleteType: 'жок кылды',
            addType: 'кошту'
        },
        requestInfo: {
            requestInfoTitle: 'Өтүнүч жөнүндө маалымат',
            requestInfoUser: 'Колдонуучу',
            requestInfoPhone: 'Телефон',
            requestInfoDate: 'Түзүүнүн датасы',
            requestInfoStatus: 'Даража',
            requestInfoMarket: 'Дүкөн',
            requestInfoAddress: 'Дареги',
            requestInfoCoord: 'Координаттар',
            requestInfoProducts: 'Продукттар',
            requestInfoProductsTitle: 'Аталышы',
            requestInfoProductsQty: 'Саны',
            requestInfoRefrigerator: 'Муздаткыч',
            refrigeratorNec: 'Кереги бар',
            refrigeratorNotNec: 'Кереги жок',
            closeBtn: 'Өтүнүчтү жабуу',
            requestInfoCourier: 'Дайындалган экспедитор',
            requestInfoCourierDate: 'Дайындоо күнү',
            courierName: 'Аты',
            courierPhone: 'Телефон',
            courierInfo: 'Экспедитордун маалыматы',
            deleteCourierBtn: 'Экспедиторду жок кылуу',
            nominateCourierBtn: 'Экспедиторго дайындал',
            fridgeAvail: 'Бар',
            fridgeNotAvail: 'Жок',
            nomBtn: 'Дайында',
            deleteClosedRequest: 'Өтүнүчтү жок кыллу',
            modal: 'Экспедиторду тандаңыз'
        },
        requestList: {
            tableUser: 'Колдонуучу',
            tableDate: 'Датасы',
            tableStatus: 'Даража',
        },
        requestListItem: {
            label_1: 'Күтүүдө',
            label_2: 'Аткаруучуда',
            label_3: 'Жабык'
        },
        userInfo: {
            userInfoTitle: 'Колдонуучунун маалыматы',
            userInfoRole: 'Кызматы',
            userInfoName: 'Колдонуучу',
            userInfoPhone: 'Телефон',
            userInfoMarket: 'Дүкөндүн аты',
            userInfoAddress: 'Дареги',
            userInfoCoord: 'Координаттар',
            userInfoCar: 'Унаа',
            userInfoCarVolume: 'Унаанын көлөмү',
            userInfoFridge: 'Муздаткычтын болушу',
            fridgeAvail: 'Бар',
            fridgeNotAvail: 'Жок',
            groupsList: 'Топтордун тизмеси',
            permissionsList: 'Уруксаттардын тизмеси'
        },
        productsActions: {
            addProductTitle: 'Продуктту кошуу',
            addProductMessage: 'Продукт ийгиликтүү кошулду',
            editProductTitle: 'Түзөтүү',
            editProductMessage: 'Продукт ийгиликтүү өзгөрүлдү',
            deleteProductTitle: 'Жок кылуу',
            deleteProductMessage: 'Продукт ийгиликтүү жок болду'
        },
        usersActions: {
            loginUserTitle: 'Кирүү',
            loginUserMessage: 'Сиз ийгиликтүү кирдиңиз, ',
            logoutUserTitle: 'Чыгуу',
            logoutUserMessage: 'Сиз каттоо эсебиңизди ийгиликтүү калтырдыңыз',
            addUserTitle: 'Колдонуучу кошуу',
            addUserMessage: 'Колдонуучу ийгиликтүү кошулду',
            deleteUserTitle: 'Колдонуучуну жок кылуу',
            deleteUserMessage: 'Колдонуучу ийгиликтүү жок кылынды'
        },
        requestsActions: {
            createRequestTitle: 'Өтүнүчтү түзүү',
            createRequestMessage: 'Өтүнүч ийгиликтүү түзүлдү',
            editRequestTitle: 'Түзөтүү',
            editRequestMessage: 'Өтүнүч ийгиликтүү түзөтүлдү',
            deleteRequestTitle: 'Жок кылуу',
            deleteRequestMessage: 'Өтүнүч ийгиликтүү жок кылынды'
        },
        statistic: {
            statisticTitle: 'Сатып алуу статистикасы',
            statisticSearchFieldTitle: 'Киргизилген күндөрдүн санын статистикасын алуу',
            salesStatistics: 'Сатуу статистикасы',
            optionName1: 'Продукттар',
            optionName2: 'Колдонуучулар',
            labelType: 'Түрү',
            labelDoc: 'Документ',
            labelFrom: 'Чейин',
            labelTo: 'Чейин',
        },
        editGroup: {
            title: 'Аты',
            btn: 'Түзөө'
        },
        groupActions: {
            addGroupTitle: 'Топту кошуу',
            addGroupMessage: 'Топ ийгиликтүү кошулду!'
        },
        trash: {
            trashTitle: 'Корзина',
            emptyTrashTitle: 'Корзина бул учурда бош',
            trashType1: 'Баары',
            trashType2: 'Колдонуучулар',
            trashType3: 'Өтүнүчтөр',
            trashType4: 'Продукттар',
            trashType5: 'Топтор',
            btnType1: 'Жаңыдан эскиге',
            btnType2: 'Эскиден жаңыга',
            autoCompleteLabel: 'Түрүн тандоо',
            tableTitle: 'Аты',
            tableDate: 'Датасы',
            request: 'Өтүнүч'
        },
        mainPageMap: {
            title: 'Соода түйүндөрүнүн картасы'
        }
    }
};