export const wordList = {
    ru: {
        necessarily: 'Обязательно',
        notNecessary: 'Не обязательно',
        productList: {
            name: 'Имя',
            quantity: 'Количество',
            price: 'Цена',
            isRefrigeratorRequired: 'Наличие холодильника для перевозки',
            searchProduct: 'Поиск продуктов',
            addNewProduct: 'Добавить новые продукты',
            productListTitle: 'Список продуктов'
        },
        loginBtn: 'Войти',
        authUserToolBar: {
            requestBtn: 'Подать заявку',
            greeting: 'Привет',
            logoutBtn: 'Выйти',
        },
        navigation: {
            logo: 'Караван',
            groupList: 'Группы',
            userList: 'Пользователи',
            requestList: 'Список заявок',
            historyList: 'История'
        },
        login: {
            loginTitle: 'Войти',
            loginBtn: 'Войти',
            userTitle: 'Имя пользователя',
            password: 'Пароль',
            usernamePlaceholder: 'Введите имя пользователя',
            passwordPlaceholder: 'Введите пароль'
        },
        usersList: {
            searchTitle: 'Поиск пользователя',
            addUserBtn: 'Добавить пользователя',
            tableName: 'Имя',
            tableLogin: 'Логин',
            tablePhone: 'Телефон',
            tableCompanyName: 'Название компании',
            tableAddress: 'Адрес',
            tableRole: 'Роль',
            tableCarName: 'Название машины',
            tableCarVolume: 'Объем машины',
            tableRefrigerator: 'Наличие холодильника',
            tableRefrigeratorAvailability: 'Есть',
            listItemUsers: 'Все',
        },
        groupsList: {
            listGroupTitle: 'Список групп',
            addGroupBtn: 'Добавить группу',
            tableGroupTitle: 'Название',
            tableGroupQty: 'Количество участников',
            addUsersBtn: 'Добавить пользователей'
        },
        groupInfo: {
            info: 'Информация о группе',
            groupTitle: 'Название группы',
            groupPermits: 'Список разрешений',
            groupUsers: 'Участники',
            groupUserName: 'Имя',
            groupUserInfo: 'Информация о пользователе',
            addUserToGroup: 'Пользователи которых можно добавить',
            addUserToGroupUserName: 'Имя',
            addUserToGroupInfo: 'Информация',
            addUserToGroupBtn: 'Добавить в группу',
            deleteGroupBtn: 'Удалить группу',
            deleteModal: 'Вы уверены что хотите удалить эту группу?',
            deleteBtnNeg: 'Нет',
            deleteBtnPos: 'Да',
        },
        addGroup: {
            addGroupTitle: 'Добавление новой группы',
            addGroupName: 'Название группы',
            addGroupBtn: 'Добавить'
        },
        addNewRequest: {
            productsBtn: 'Доступный товар',
            createRequestTitle: 'Создать заявку',
            commentTitle: 'Комментарий',
            addRequestBtn: 'Добавить',
            createRequestBtn: 'Создать заявку',
        },
        addNewRequestItem: {
            btnTitle: 'Название',
            btnQty: 'Количество',
        },
        addProduct: {
            addProductTitle: 'Добавление продуктов',
            addProductBtn: 'Добавить',
            createProductBtn: 'Сохранить',
        },
        addProductItem: {
            inputTitle: 'Название',
            inputQty: 'Количество',
            inputPrice: 'Цена',
            inputRefrigerator: 'Необходим ли холодильник для перевозки?',
            inputImg: 'Изображение',
            inputComment: 'Причина добавления',
        },
        addUser: {
            addUserTitle: 'Добавление нового пользователя',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Отображаемое имя',
            inputRole: 'Роль',
            inputCarName: 'Марка машины',
            inputCarVolume: 'Объем машины',
            inputRefrigerator: 'Наличие холодильника',
            inputCompanyName: 'Название компании',
            inputCompanyAddress: 'Адрес компании',
            inputCoordinates: 'Координаты',
            inputAvatar: 'Avatar',
            inputComment: 'Причина добавления',
            addBtn: 'Добавить'
        },
        editProduct: {
            editProductTitle: 'Редактирование продукта',
            inputTitle: 'Название',
            inputQty: 'Количество',
            inputPrice: 'Цена',
            inputRefrigerator: 'Необходим ли холодильник для перевозки?',
            inputImg: 'Изображение',
            editProductBtn: 'Редактировать',
            deleteProductBtn: 'Удалить',
            modalDeleteTitle: 'Вы уверены что хотите удалить этот продукт?',
            modalComment: 'Комментарий',
            modalBtnNeg: 'Нет',
            modalBtnPos: 'Да',
            modalEditTitle: 'Вы уверены что хотите отредактировать этот продукт?',
        },
        editRequest: {
            editRequestTitle: 'Редактировать заявку',
            inputComment: 'Комментарий',
            addRequestBtn: 'Добавить',
            editRequestBtn: 'Редактировать заявку',
            deleteRequestBtn: 'Удалить заявку',
            modalBtnNeg: 'Нет',
            modalBtnPos: 'Да',
        },
        editRequestItems: {
            title: 'Название: ',
            qty: 'Количество: ',
            chooseProd: 'Выберите продукт',
            inputQty: 'Количество'
        },
        editUser: {
            editUserTitle: 'Редактирование пользователя',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Отображаемое имя',
            inputRole: 'Роль',
            inputCarName: 'Название машины',
            inputCarVolume: 'Объем машины',
            inputRefrigerator: 'Наличие холодильника',
            inputCompanyName: 'Название компании',
            inputCompanyAddress: 'Адрес компании',
            inputAvatar: 'Avatar',
            inputEditComment: 'Причина редактирования',
            editBtn: 'Редактировать',
            deleteBtn: 'Удалить пользователя',
            modalDeleteTitle: 'Вы уверены что хотите удалить этого пользователя?',
            inputDeleteComment: 'Причина удаления',
            modalBtnNeg: 'Нет',
            modalBtnPos: 'Да',
        },
        histories: {
            tableInfo: 'Информация',
            tableComment: 'Комментарий',
            tableType: 'Тип',
            tableDate: 'Дата',
            deleteLabel: 'Удаление',
            addLabel: 'Добавление',
            editLabel: 'Редактирование',
        },
        requestInfo: {
            requestInfoTitle: 'Информация о заявке',
            requestInfoUser: 'Пользователь',
            requestInfoPhone: 'Телефон',
            requestInfoDate: 'Дата создания',
            requestInfoStatus: 'Статус',
            requestInfoMarket: 'Магазин',
            requestInfoAddress: 'Адрес',
            requestInfoCoord: 'Координаты',
            requestInfoProducts: 'Продукты',
            requestInfoProductsTitle: 'Название',
            requestInfoProductsQty: 'Количество',
            requestInfoRefrigerator: 'Холодильник',
            refrigeratorNec: 'Нужен',
            refrigeratorNotNec: 'Не нужен',
            closeBtn: 'Закрыть заявку',
            requestInfoCourier: 'Назначенный курьер',
            requestInfoCourierDate: 'Дата назначения',
            courierName: 'Имя',
            courierPhone: 'Телефон',
            courierInfo: 'Информация о курьере',
            deleteCourierBtn: 'Удалить курьера',
            nominateCourierBtn: 'Назначить экспедитору',
            fridgeAvail: 'Есть',
            fridgeNotAvail: 'Отсутствует',
            nomBtn: 'Назначить',
        }
    },


    kg: {
        necessarily: 'Сөзсүз',
        notNecessary: 'Кереги жок',
        productList: {
            name: 'Наам',
            quantity: 'Канча',
            price: 'Баа',
            isRefrigeratorRequired: 'Ташуу үчүн муздаткычтын болушу',
            searchProduct: 'Продукцияны издөө',
            addNewProduct: 'Жаңы өнүмдөрдү кошуу',
            productListTitle: 'Продукт тизмеси'
        },
        loginBtn: 'Кирүү',
        authUserToolBar: {
            requestBtn: 'Арыз берүү',
            greeting: 'Салам',
            logoutBtn: 'Чыгуу',
        },
        navigation: {
            logo: 'Караван',
            groupList: 'Топтор',
            userList: 'Колдонуучулар',
            requestList: 'Арыздар',
            historyList: 'Тарыхы'
        },
        login: {
            loginTitle: 'Кирүү',
            loginBtn: 'Кирүү',
            userTitle: 'Колдонуучунун аты',
            password: 'Пароль',
            usernamePlaceholder: 'Колдонуучунун атын киргизгиле',
            passwordPlaceholder: 'Пароль киргизгиле'
        },
        usersList: {
            searchTitle: 'Колдонуучуну издөө',
            addUserBtn: 'Колдонуучуну кошуу',
            tableName: 'Аты',
            tableLogin: 'Логин',
            tablePhone: 'Телефон',
            tableCompanyName: 'Компаниянын аты',
            tableAddress: 'Дареги',
            tableRole: 'Ролу',
            tableCarName: 'Унаанын аты',
            tableCarVolume: 'Унаанын көлөмү',
            tableRefrigerator: 'Муздаткычтын катышуусу',
            tableRefrigeratorAvailability: 'Бар',
            listItemUsers: 'Баары'
        },
        groupsList: {
            listGroupTitle: 'Топтордун тизмеси',
            addGroupBtn: 'Тобун кошуу',
            tableGroupTitle: 'Аты',
            tableGroupQty: 'Катышуучулардын саны',
            addUsersBtn: 'Колдонуучуларды кошуу'
        },
        groupInfo: {
            info: 'Тобунун маалыматы',
            groupTitle: 'Тобунун аты',
            groupPermits: 'Уруксат тизмеси',
            groupUsers: 'Катышуучулар',
            groupUserName: 'Аты',
            groupUserInfo: 'Катышуучунун маалыматы',
            addUserToGroup: 'Колдонуучуларды кошо аласыз',
            addUserToGroupUserName: 'Аты',
            addUserToGroupInfo: 'Маалымат',
            addUserToGroupBtn: 'Тобуна кошуу',
            deleteGroupBtn: 'Тобун жок кылуу',
            deleteModal: 'Бул топту чын эле жок кылгыңыз келеби?',
            deleteBtnNeg: 'Жок',
            deleteBtnPos: 'Ооба',
        },
        addGroup: {
            addGroupTitle: 'Жаңы топ кошуу',
            addGroupName: 'Тобунун аты',
            addGroupBtn: 'Кошуу'
        },
        addNewRequest: {
            productsBtn: 'Жеткиликтүү нерсе',
            createRequestTitle: 'Арыз түзүү',
            commentTitle: 'Түшүндүрмө',
            addRequestBtn: 'Кошуу',
            createRequestBtn: 'Арыз түзүү',
        },
        addNewRequestItem: {
            btnTitle: 'Аты',
            btnQty: 'Саны',
        },
        addProduct: {
            addProductTitle: 'Продуктту кошуу',
            addProductBtn: 'Кошуу',
            createProductBtn: 'Түзүү',
        },
        addProductItem: {
            inputTitle: 'Аты',
            inputQty: 'Саны',
            inputPrice: 'Баа',
            inputRefrigerator: 'Ташуу үчүн муздаткыч керекпи?',
            inputImg: 'Сүрөт',
            inputComment: 'Кошуунун себеби',
        },
        addUser: {
            addUserTitle: 'Жаңы колдонуучу кошуу',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Аты',
            inputRole: 'Ролу',
            inputCarName: 'Унаанын модели',
            inputCarVolume: 'Унаанын көлөмү',
            inputRefrigerator: 'Муздаткычтын болушу',
            inputCompanyName: 'Компаниянын аты',
            inputCompanyAddress: 'Компаниянын дареги',
            inputCoordinates: 'Координаттар',
            inputAvatar: 'Avatar',
            inputComment: 'Кошуунун себеби',
            addBtn: 'Кошуу'
        },
        editProduct: {
            editProductTitle: 'Өнүмдү түзөтүү',
            inputTitle: 'Аты',
            inputQty: 'Саны',
            inputPrice: 'Баасы',
            inputRefrigerator: 'Ташуу үчүн муздаткыч керекпи?',
            inputImg: 'Сүрөтү',
            editProductBtn: 'Түзөө',
            deleteProductBtn: 'Жок кылуу',
            modalDeleteTitle: 'Бул өнүмдү чын эле алып салгыңыз келеби?',
            modalComment: 'Түшүндүрмө',
            modalBtnNeg: 'Жок',
            modalBtnPos: 'Ооба',
            modalEditTitle: 'Бул өнүмдү чын эле түзөткүңүз келеби?',
        },
        editRequest: {
            editRequestTitle: 'Арызды түзөтүү',
            inputComment: 'Түшүндүрмө',
            addRequestBtn: 'Кошуу',
            editRequestBtn: 'Арызды түзөтүү',
            deleteRequestBtn: 'Арызды жок кылуу',
            modalBtnNeg: 'Жок',
            modalBtnPos: 'Ооба',
        },
        editRequestItems: {
            title: 'Аты: ',
            qty: 'Саны: ',
            chooseProd: 'Продуктту тандаңыз',
            inputQty: 'Саны'
        },
        editUser: {
            editUserTitle: 'Колдонуучу түзөтүүсү',
            inputLogin: 'Логин',
            inputPassword: 'Пароль',
            inputName: 'Аты',
            inputRole: 'Ролу',
            inputCarName: 'Унаанын модели',
            inputCarVolume: 'Унаанын көлөмү',
            inputRefrigerator: 'Муздаткычтын болушу',
            inputCompanyName: 'Компаниянын аты',
            inputCompanyAddress: 'Компаниянын дареги',
            inputAvatar: 'Avatar',
            inputEditComment: 'Түзөтүүнүн себеби',
            editBtn: 'Түзөө',
            deleteBtn: 'Колдонуучуну жок кылуу',
            modalDeleteTitle: 'Чын эле бул колдонуучуну жок кылгыңыз келеби?',
            inputDeleteComment: 'Жок кылуунун себеби',
            modalBtnNeg: 'Жок',
            modalBtnPos: 'Ооба',
        },
        histories: {
            tableInfo: 'Маалымат',
            tableComment: 'Түшүндүрмө',
            tableType: 'Түрү',
            tableDate: 'Датасы',
            deleteLabel: 'Жок кылуу',
            addLabel: 'Кошуу',
            editLabel: 'Түзөтүү',
        },
        requestInfo: {
            requestInfoTitle: 'Арыз жөнүндө маалымат',
            requestInfoUser: 'Колдонуучу',
            requestInfoPhone: 'Телефон',
            requestInfoDate: 'Түзүүнүн датасы',
            requestInfoStatus: 'Статус',
            requestInfoMarket: 'Дүкөн',
            requestInfoAddress: 'Дареги',
            requestInfoCoord: 'Координаттар',
            requestInfoProducts: 'Продукттар',
            requestInfoProductsTitle: 'Аталышы',
            requestInfoProductsQty: 'Саны',
            requestInfoRefrigerator: 'Муздаткыч',
            refrigeratorNec: 'Кереги бар',
            refrigeratorNotNec: 'Кереги жок',
            closeBtn: 'Арызды жабуу',
            requestInfoCourier: 'Дайындалган экспедитор',
            requestInfoCourierDate: 'Дайындоо күнү',
            courierName: 'Аты',
            courierPhone: 'Телефон',
            courierInfo: 'Экспедитордун маалыматы',
            deleteCourierBtn: 'Экспедиторду жок кылуу',
            nominateCourierBtn: 'Экспедиторго дайындал',
            fridgeAvail: 'Бар',
            fridgeNotAvail: 'Жок',
            nomBtn: 'Дайында',
        }
    }
};